"""The shared line classifier every prose check consumes.

Produced once per file. Five checks each with their own idea of where a fenced
block ends will disagree on an edge case, and the reflow will then rewrite a
line the lint told the author was code. One classifier makes that class of bug
impossible rather than unlikely.

The classifier fails closed: an unbalanced fence, an unterminated HTML comment
or frontmatter that never closes yields a :class:`ClassifyError`, and the file
is skipped by every check — and never written to.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace
from enum import StrEnum
from typing import TYPE_CHECKING

from mdd.prose.inline import LinkRef, Span, scan

if TYPE_CHECKING:
    from collections.abc import Sequence

_BQ = re.compile(r"(?: {0,3}>[ \t]?)+")
_FENCE = re.compile(r"^[ \t]*(`{3,}|~{3,})")
_ATX = re.compile(r"^ {0,3}#{1,6}(\s|$)")
_TBREAK = re.compile(r"^ {0,3}([-*_])[ \t]*(?:\1[ \t]*){2,}$")
_SETEXT = re.compile(r"^ {0,3}(?:=+|-+)[ \t]*$")
_LIST = re.compile(r"^([ \t]*)([-*+]|\d{1,9}[.)])([ \t]+)(?=\S)")
_LIST_BARE = re.compile(r"^([ \t]*)([-*+]|\d{1,9}[.)])[ \t]*$")
_LINK_DEF = re.compile(r"^ {0,3}\[[^\]^]+\]:[ \t]*\S+")
_FOOTNOTE_DEF = re.compile(r"^([ \t]*\[\^[^\]]+\]:[ \t]+)(?=\S)")
_HTML_BLOCK = re.compile(r"^ {0,3}</?[A-Za-z!?]")
_DELIM_ROW = re.compile(r"^[ \t]*\|?[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)+\|?[ \t]*$")
_MATH_FENCE = re.compile(r"^ {0,3}\$\$")
_DIV_FENCE = re.compile(r"^[ \t]*:{3,}")
_ALERT_MARKER = re.compile(r"^\[!\w+\]$")
_MANAGED_CALLOUT = re.compile(r"^\*\*(?:Confluence|SharePoint) export\*\*")
_MDD_FOOTER = re.compile(r"^\*Generated by mdd")
_INDENT = re.compile(r"^[ \t]*")

_INDENTED_CODE_COLUMN = 4


class LineClass(StrEnum):
    """What one source line is."""

    FRONTMATTER = "frontmatter"
    FENCED_CODE = "fenced-code"
    INDENTED_CODE = "indented-code"
    HTML_BLOCK = "html-block"
    HTML_COMMENT = "html-comment"
    TABLE = "table"
    BLOCK_QUOTE = "block-quote"
    HEADING = "heading"
    THEMATIC_BREAK = "thematic-break"
    LINK_DEF = "link-target"
    MATH = "math"
    BLANK = "blank"
    #: A ``:::``/``::::`` fenced-div marker (callouts, layouts). Its body is
    #: ordinary prose and is reflowed; the marker line itself never is.
    DIV_MARKER = "div-marker"
    #: A region a rewriter must pass through byte-for-byte: an mdd-managed
    #: export callout, or a callout marker line such as ``> [!NOTE]``. Joining
    #: one into the paragraph below it changes what the file renders as.
    MANAGED = "managed-region"
    PROSE = "prose"


@dataclass(frozen=True)
class Line:
    """One classified source line.

    ``prefix`` is the leading bytes a rewriter must preserve verbatim — block
    quote markers, a list marker, the indent. ``cont_prefix`` is what a
    generated continuation line must start with so the block still parses.
    """

    number: int
    text: str
    cls: LineClass
    prefix: str = ""
    cont_prefix: str = ""
    masks: tuple[Span, ...] = ()
    links: tuple[LinkRef, ...] = ()
    block: int = -1
    hard_break: bool = False

    @property
    def content(self) -> str:
        """The line's text with its preserved prefix removed."""
        return self.text[len(self.prefix) :]


@dataclass(frozen=True)
class Classified:
    """A whole file's classification, plus the byte-level facts a writer needs."""

    lines: tuple[Line, ...]
    newline: str
    final_newline: bool


@dataclass(frozen=True)
class ClassifyError:
    """Why a file could not be classified.

    A value rather than an exception: one unparseable file must not end a
    corpus-wide run.
    """

    line: int
    reason: str


def newline_style(text: str) -> str | None:
    """Return the file's single line-ending convention, or ``None`` if it mixes them.

    Splitting on one terminator when the file uses two leaves the other embedded
    inside a "line", so the classifier mis-scans it and a rewriter silently drops
    or moves bytes. There is no correct choice to make on the user's behalf, so a
    mixed file fails closed instead.
    """
    crlf = text.count("\r\n")
    counts = {
        "\r\n": crlf,
        "\n": text.count("\n") - crlf,
        "\r": text.count("\r") - crlf,
    }
    present = [style for style, count in counts.items() if count]
    if len(present) > 1:
        return None
    return present[0] if present else "\n"


def split_lines(text: str) -> tuple[list[str], str, bool]:
    """Split *text* into lines, returning its newline and whether one trails."""
    newline = newline_style(text) or "\n"
    final_newline = text.endswith(newline)
    body = text[: -len(newline)] if final_newline else text
    if not body and final_newline:
        return [], newline, True
    return body.split(newline), newline, final_newline


def join_lines(lines: list[str], newline: str, *, final_newline: bool) -> str:
    """Inverse of :func:`split_lines`."""
    body = newline.join(lines)
    return body + newline if final_newline else body


def _strip_quote(raw: str) -> tuple[str, str]:
    """Split *raw* into its block-quote prefix and the remainder."""
    match = _BQ.match(raw)
    if match is None or match.end() == 0:
        return "", raw
    return raw[: match.end()], raw[match.end() :]


#: The only characters Markdown treats as horizontal whitespace. `str.strip()`
#: with no argument also eats U+00A0 and friends, which are *content*: deleting
#: a leading no-break space turns a paragraph into whatever its first character
#: then spells — a fence, a heading, a list item.
MD_SPACE = " \t"

_TAB_STOP = 4


def _indent_bytes(text: str) -> str:
    """Return *text*'s leading indent verbatim, so a rewriter can re-emit it."""
    return _INDENT.match(text).group(0)  # pyright: ignore[reportOptionalMemberAccess]


def _indent_columns(text: str) -> int:
    """Return the indent's width in columns, expanding tabs to 4-column stops.

    Character count is the wrong measure: a single leading tab is four columns,
    which is the difference between a paragraph and an indented code block.
    """
    column = 0
    for char in _indent_bytes(text):
        column += _TAB_STOP - (column % _TAB_STOP) if char == "\t" else 1
    return column


def _hard_break(text: str) -> bool:
    return text.endswith(("  ", "\\")) and bool(text.strip(MD_SPACE))


@dataclass
class _State:
    """Mutable block-level scanner state."""

    in_frontmatter: bool = False
    fence: str | None = None
    fence_quote_depth: int = 0
    fence_indent: int = 0
    in_comment: bool = False
    in_math: bool = False
    in_html_block: bool = False
    in_indented_code: bool = False
    list_content_col: int | None = None
    after_blank: bool = True
    open_at: int = 0


def _prose_line(number: int, raw: str, quote: str, rest: str) -> Line:
    """Build a PROSE line, deriving the prefix and continuation prefix."""
    marker = _LIST.match(rest) or _FOOTNOTE_DEF.match(rest)
    if marker is not None:
        prefix = quote + marker.group(0)
        return Line(
            number=number,
            text=raw,
            cls=LineClass.PROSE,
            prefix=prefix,
            cont_prefix=quote + " " * (len(prefix) - len(quote)),
            hard_break=_hard_break(raw),
        )
    indent = _indent_bytes(rest)
    return Line(
        number=number,
        text=raw,
        cls=LineClass.PROSE,
        prefix=quote + indent,
        cont_prefix=quote + indent,
        hard_break=_hard_break(raw),
    )


def _quote_depth(quote: str) -> int:
    return quote.count(">")


def _opens_fence(rest: str, fence: re.Match[str]) -> bool:
    """True when a fence-shaped line really opens a fenced block.

    CommonMark 4.5: the info string of a backtick fence may not contain a
    backtick. Without that condition a paragraph beginning ``` ```a `b` ``` ```
    opened a block, and everything up to the next fence-shaped line — including
    a genuine code block — became prose the fixers would rewrite.
    """
    return fence.group(1)[0] != "`" or "`" not in rest[fence.end() :]


def _closes_fence(rest: str, quote: str, state: _State) -> bool:
    """True when this line closes the open fence.

    A closer must sit in the same block-quote container as the opener and be no
    more than three columns further indented. Without those two conditions a
    ``>``-prefixed or deeply indented ``` inside a fenced block closed it, and
    the remainder of the code became prose the fixers would rewrite.
    """
    fence = state.fence
    if fence is None or _quote_depth(quote) != state.fence_quote_depth:
        return False
    closer = _FENCE.match(rest)
    if closer is None or closer.group(1)[0] != fence[0] or len(closer.group(1)) < len(fence):
        return False
    if _indent_columns(rest) > state.fence_indent + 3:
        return False
    return not rest[closer.end() :].strip(MD_SPACE)


def _continuation(number: int, raw: str, quote: str, rest: str, state: _State) -> Line | None:
    """Classify *raw* against an open multi-line construct, or return ``None``."""
    if state.in_frontmatter:
        state.in_frontmatter = rest.strip(MD_SPACE) not in ("---", "...")
        return Line(number, raw, LineClass.FRONTMATTER)
    if state.fence is not None:
        if _closes_fence(rest, quote, state):
            state.fence = None
        return Line(number, raw, LineClass.FENCED_CODE)
    if state.in_comment:
        state.in_comment = "-->" not in rest
        return Line(number, raw, LineClass.HTML_COMMENT)
    return _continuation_tail(number, raw, rest, state)


def _continuation_tail(number: int, raw: str, rest: str, state: _State) -> Line | None:
    """The second half of :func:`_continuation`: math blocks and HTML blocks."""
    if state.in_math:
        # Symmetric with the opener: a `$$` carrying anything else, including a
        # no-break space, does not close the block. Closing early hands the rest
        # of the maths to the fixers as prose.
        state.in_math = rest.strip(MD_SPACE) != "$$"
        return Line(number, raw, LineClass.MATH)
    if not state.in_html_block:
        return None
    if rest.strip(MD_SPACE):
        return Line(number, raw, LineClass.HTML_BLOCK)
    state.in_html_block = False
    return Line(number, raw, LineClass.BLANK)


def _open_block(number: int, raw: str, quote: str, rest: str, state: _State) -> Line | None:
    """Classify *raw* as the opening line of a multi-line construct, or ``None``."""
    fence = _FENCE.match(rest)
    if fence is not None and _opens_fence(rest, fence):
        state.fence = fence.group(1)
        state.fence_quote_depth = _quote_depth(quote)
        state.fence_indent = _indent_columns(rest)
        state.open_at = number
        return Line(number, raw, LineClass.FENCED_CODE)
    stripped = rest.lstrip()
    if stripped.startswith("<!--"):
        if "-->" not in stripped[4:]:
            state.in_comment = True
            state.open_at = number
        return Line(number, raw, LineClass.HTML_COMMENT)
    if _MATH_FENCE.match(rest):
        if rest.strip(MD_SPACE) == "$$":
            state.in_math = True
            state.open_at = number
        return Line(number, raw, LineClass.MATH)
    # A fenced-div marker. Its body is ordinary prose and is reflowed; the
    # marker line is not. Joining `:::callout-tip` into the paragraph below it
    # destroys the callout, which is a first-class construct in the IR.
    if _DIV_FENCE.match(rest):
        return Line(number, raw, LineClass.DIV_MARKER)
    # CommonMark condition 7: a bare-tag HTML block cannot interrupt a
    # paragraph. Without the blank-line requirement a mid-paragraph line
    # starting `<https://…>` swallowed the rest of the paragraph, exempting it
    # from every check.
    if state.after_blank and _HTML_BLOCK.match(rest):
        state.in_html_block = True
        return Line(number, raw, LineClass.HTML_BLOCK)
    return None


def _close_list(rest: str, state: _State) -> None:
    """Close the open list item when *rest* starts a block flush against the margin.

    Called for every fresh line, not only the ones that end up as prose. A
    heading, a fence or a thematic break at column zero ends the list just as a
    paragraph does, and leaving the content column set after one raised the
    indented-code floor so a genuine four-space code block read as prose — and
    the fixers then rewrote its interior.
    """
    if rest.strip(MD_SPACE) and _indent_columns(rest) == 0:
        state.list_content_col = None


def _track_list(rest: str, state: _State) -> None:
    """Update the innermost open list item's content column."""
    marker = _LIST.match(rest) or _LIST_BARE.match(rest)
    if marker is not None:
        state.list_content_col = len(marker.group(0))
        return
    _close_list(rest, state)


def _is_indented_code(rest: str, state: _State) -> bool:
    """True when *rest* belongs to an indented code block.

    An indented code block *opens* only after a blank line, but it *continues*
    for as long as the indent holds. Requiring a preceding blank on every line
    classified only the block's first line as code and handed the rest to the
    rewriters as prose.
    """
    if not state.after_blank and not state.in_indented_code:
        return False
    floor = _INDENTED_CODE_COLUMN + (state.list_content_col or 0)
    return _indent_columns(rest) >= floor


def _single_line_class(rest: str, state: _State) -> LineClass | None:
    """Return the class of a line that is a whole block by itself, or ``None``."""
    if _ATX.match(rest):
        return LineClass.HEADING
    if _TBREAK.match(rest):
        return LineClass.THEMATIC_BREAK
    if _is_indented_code(rest, state):
        return LineClass.INDENTED_CODE
    return LineClass.LINK_DEF if _LINK_DEF.match(rest) else None


def _classify_fresh(number: int, raw: str, quote: str, rest: str, state: _State) -> Line:
    """Classify a line that is not inside any open multi-line construct."""
    # Indented code is tested first: its contents are literal, so a line inside
    # it that happens to read as `<!--` or a fence must not open a construct.
    if _is_indented_code(rest, state):
        return Line(number, raw, LineClass.INDENTED_CODE)
    opened = _open_block(number, raw, quote, rest, state)
    if opened is not None:
        _close_list(rest, state)
        return opened
    single = _single_line_class(rest, state)
    if single is not None:
        _close_list(rest, state)
        return Line(number, raw, single)
    _track_list(rest, state)
    if not rest.strip(MD_SPACE):
        return Line(number, raw, LineClass.BLOCK_QUOTE if quote else LineClass.BLANK)
    return _prose_line(number, raw, quote, rest)


def _scan_blocks(raw_lines: list[str]) -> tuple[list[Line], ClassifyError | None]:
    """Run the block-level state machine over *raw_lines*."""
    state = _State()
    out: list[Line] = []
    for index, raw in enumerate(raw_lines):
        number = index + 1
        if number == 1 and raw.rstrip(MD_SPACE) == "---":
            state.in_frontmatter = True
            state.open_at = 1
            out.append(Line(1, raw, LineClass.FRONTMATTER))
            continue
        quote, rest = _strip_quote(raw)
        line = _continuation(number, raw, quote, rest, state) or _classify_fresh(
            number, raw, quote, rest, state
        )
        blank = line.cls in (LineClass.BLANK, LineClass.BLOCK_QUOTE)
        state.after_blank = blank
        # A blank line does not end an indented code block — it is content
        # inside one — so the flag survives a blank and only a shallower
        # non-blank line clears it.
        if not blank:
            state.in_indented_code = line.cls is LineClass.INDENTED_CODE
        out.append(line)
    if state.in_frontmatter:
        return out, ClassifyError(state.open_at, "frontmatter block never closes")
    if state.fence is not None:
        return out, ClassifyError(state.open_at, "fenced code block never closes")
    if state.in_comment:
        return out, ClassifyError(state.open_at, "HTML comment never closes")
    if state.in_math:
        return out, ClassifyError(state.open_at, "math block never closes")
    return out, None


def _reclaim_code_blanks(lines: list[Line]) -> None:
    """Reclassify a blank line that sits *between* two indented-code lines.

    Such a line is content of the code block, not a paragraph separator, so
    ``blank-run`` must not delete it. Decided in a post-pass because it needs to
    know whether the code block resumes, which the forward scan cannot.
    """
    #: One forward pass. Re-scanning the whole file from each blank line was
    #: quadratic: 32k lines of ordinary prose spent 0.6s here alone.
    run: list[int] = []
    in_code = False
    for index, line in enumerate(lines):
        if line.cls is LineClass.BLANK:
            run.append(index)
            continue
        if in_code and line.cls is LineClass.INDENTED_CODE:
            for blank in run:
                lines[blank] = replace(lines[blank], cls=LineClass.INDENTED_CODE)
        run.clear()
        in_code = line.cls is LineClass.INDENTED_CODE


def _apply_setext(lines: list[Line]) -> None:
    """Reclassify a paragraph followed by an ``===``/``---`` rule as a heading."""
    for index, line in enumerate(lines):
        if index == 0 or line.cls not in (LineClass.PROSE, LineClass.THEMATIC_BREAK):
            continue
        _, rest = _strip_quote(line.text)
        previous = lines[index - 1]
        if not _SETEXT.match(rest) or previous.cls is not LineClass.PROSE:
            continue
        # A setext underline closes a paragraph, not a list item. Without this
        # `- a\n- b\n---` turned the whole list into a heading, inventing
        # anchors and an `ambiguous-anchor` finding for text that is not a
        # heading at all.
        if _LIST.match(_strip_quote(previous.text)[1]):
            continue
        lines[index] = replace(line, cls=LineClass.HEADING, prefix="", cont_prefix="")
        back = index - 1
        while back >= 0 and lines[back].cls is LineClass.PROSE:
            lines[back] = replace(lines[back], cls=LineClass.HEADING, prefix="", cont_prefix="")
            back -= 1


def _apply_tables(lines: list[Line]) -> None:
    """Reclassify a header row, its delimiter row and the body rows as a table."""
    for index, line in enumerate(lines):
        _, rest = _strip_quote(line.text)
        if index == 0 or not _DELIM_ROW.match(rest) or "|" not in rest:
            continue
        header = lines[index - 1]
        if header.cls is not LineClass.PROSE or "|" not in header.text:
            continue
        lines[index - 1] = replace(header, cls=LineClass.TABLE, prefix="", cont_prefix="")
        lines[index] = replace(line, cls=LineClass.TABLE, prefix="", cont_prefix="")
        forward = index + 1
        while (
            forward < len(lines)
            and lines[forward].cls is LineClass.PROSE
            and "|" in lines[forward].text
        ):
            lines[forward] = replace(lines[forward], cls=LineClass.TABLE, prefix="", cont_prefix="")
            forward += 1


def _mark_managed(lines: list[Line], index: int) -> None:
    lines[index] = replace(lines[index], cls=LineClass.MANAGED, prefix="", cont_prefix="")


def _apply_managed(lines: list[Line]) -> None:
    """Reclassify mdd-managed export callouts, the mdd footer, and callout markers.

    These are matched on export and stripped before a push, so a reflow that
    reshaped one could push it into the page body.
    """
    for index, line in enumerate(lines):
        if line.cls not in (LineClass.PROSE, LineClass.BLOCK_QUOTE):
            continue
        quote, rest = _strip_quote(line.text)
        if not quote:
            continue
        content = rest.strip(MD_SPACE)
        if _ALERT_MARKER.match(content):
            _mark_managed(lines, index)
            continue
        if not _MANAGED_CALLOUT.match(content) and not _MDD_FOOTER.match(content):
            continue
        forward = index
        while forward < len(lines) and _strip_quote(lines[forward].text)[0]:
            _mark_managed(lines, forward)
            forward += 1


def _assign_blocks(lines: list[Line]) -> None:
    """Group contiguous prose lines that belong to the same logical paragraph."""
    previous: Line | None = None
    counter = 0
    for index, line in enumerate(lines):
        if line.cls is not LineClass.PROSE:
            previous = None
            continue
        if previous is not None and previous.cont_prefix == line.prefix:
            block = previous.block
        else:
            counter += 1
            block = counter
        lines[index] = replace(line, block=block)
        previous = lines[index]


_UNMASKED_CLASSES = (LineClass.FRONTMATTER, LineClass.FENCED_CODE, LineClass.INDENTED_CODE)


def block_text(lines: Sequence[Line]) -> tuple[str, list[int]]:
    """Unwrap a prose block to one logical string, plus each line's start offset.

    Masking must run over this string rather than per line: a hard-wrapped
    paragraph can split a code span or a link across a soft break, and a
    per-line scan sees two unbalanced halves instead of one construct.
    """
    starts: list[int] = []
    parts: list[str] = []
    position = 0
    for line in lines:
        if parts:
            position += 1
        starts.append(position)
        content = line.text[len(line.prefix) :].rstrip(MD_SPACE)
        parts.append(content)
        position += len(content)
    return " ".join(parts), starts


@dataclass(frozen=True)
class _Bound:
    """Where one line of a block sits within the block's joined text."""

    index: int
    start: int
    length: int
    shift: int

    def clip(self, span: Span) -> Span | None:
        low, high = max(span.start, self.start), min(span.end, self.start + self.length)
        return Span(low + self.shift, high + self.shift, span.cls) if low < high else None

    def holds(self, position: int) -> bool:
        return self.start <= position < self.start + self.length


def _block_bounds(lines: Sequence[Line], indices: Sequence[int]) -> list[_Bound]:
    block = [lines[index] for index in indices]
    _, starts = block_text(block)
    return [
        _Bound(
            index=index,
            start=starts[offset],
            length=len(block[offset].content.rstrip(MD_SPACE)),
            shift=len(block[offset].prefix) - starts[offset],
        )
        for offset, index in enumerate(indices)
    ]


def _spread_masks(lines: list[Line], indices: Sequence[int]) -> None:
    """Scan one block's joined text and project the spans back onto its lines."""
    joined, _ = block_text([lines[index] for index in indices])
    result = scan(joined)
    for bound in _block_bounds(lines, indices):
        spans = [clipped for span in result.masks if (clipped := bound.clip(span)) is not None]
        links = [
            LinkRef(ref.start + bound.shift, ref.target)
            for ref in result.links
            if bound.holds(ref.start)
        ]
        lines[bound.index] = replace(lines[bound.index], masks=tuple(spans), links=tuple(links))


def _apply_masks(lines: list[Line]) -> None:
    """Mask inline constructs: per block for prose, per line for everything else."""
    blocks: dict[int, list[int]] = {}
    for index, line in enumerate(lines):
        if line.cls is LineClass.PROSE:
            blocks.setdefault(line.block, []).append(index)
        elif line.cls not in _UNMASKED_CLASSES:
            result = scan(line.text, start=len(line.prefix))
            lines[index] = replace(line, masks=result.masks, links=result.links)
    for indices in blocks.values():
        _spread_masks(lines, indices)


def classify(text: str) -> Classified | ClassifyError:
    """Classify *text* line by line, or explain why it cannot be classified."""
    if newline_style(text) is None:
        return ClassifyError(1, "file mixes line endings")
    raw_lines, newline, final_newline = split_lines(text)
    lines, error = _scan_blocks(raw_lines)
    if error is not None:
        return error
    _reclaim_code_blanks(lines)
    _apply_setext(lines)
    _apply_tables(lines)
    _apply_managed(lines)
    _assign_blocks(lines)
    _apply_masks(lines)
    return Classified(lines=tuple(lines), newline=newline, final_newline=final_newline)
