"""The shared line classifier every prose check consumes.

Produced once per file. Five checks each with their own idea of where a fenced
block ends will disagree on an edge case, and the reflow will then rewrite a
line the lint told the author was code. One classifier makes that class of bug
impossible rather than unlikely.

The classifier fails closed: an unbalanced fence, an unterminated HTML comment
or frontmatter that never closes yields a :class:`ClassifyError`, and the file
is skipped by every check — and never written to.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace
from enum import StrEnum
from typing import TYPE_CHECKING

from mdd.prose.inline import LinkRef, Span, scan

if TYPE_CHECKING:
    from collections.abc import Sequence

_BQ = re.compile(r"(?: {0,3}>[ \t]?)+")
_FENCE = re.compile(r"^[ \t]*(`{3,}|~{3,})")
_ATX = re.compile(r"^ {0,3}#{1,6}(\s|$)")
_TBREAK = re.compile(r"^ {0,3}([-*_])[ \t]*(?:\1[ \t]*){2,}$")
_SETEXT = re.compile(r"^ {0,3}(?:=+|-+)[ \t]*$")
_LIST = re.compile(r"^([ \t]*)([-*+]|\d{1,9}[.)])([ \t]+)(?=\S)")
_LIST_BARE = re.compile(r"^([ \t]*)([-*+]|\d{1,9}[.)])[ \t]*$")
_LINK_DEF = re.compile(r"^ {0,3}\[[^\]^]+\]:[ \t]*\S+")
_FOOTNOTE_DEF = re.compile(r"^([ \t]*\[\^[^\]]+\]:[ \t]+)(?=\S)")
_HTML_BLOCK = re.compile(r"^ {0,3}</?[A-Za-z!?]")
_DELIM_ROW = re.compile(r"^[ \t]*\|?[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)+\|?[ \t]*$")
_MATH_FENCE = re.compile(r"^ {0,3}\$\$")
_ALERT_MARKER = re.compile(r"^\[!\w+\]$")
_MANAGED_CALLOUT = re.compile(r"^\*\*(?:Confluence|SharePoint) export\*\*")
_MDD_FOOTER = re.compile(r"^\*Generated by mdd")
_INDENT = re.compile(r"^[ \t]*")

_INDENTED_CODE_COLUMN = 4


class LineClass(StrEnum):
    """What one source line is."""

    FRONTMATTER = "frontmatter"
    FENCED_CODE = "fenced-code"
    INDENTED_CODE = "indented-code"
    HTML_BLOCK = "html-block"
    HTML_COMMENT = "html-comment"
    TABLE = "table"
    BLOCK_QUOTE = "block-quote"
    HEADING = "heading"
    THEMATIC_BREAK = "thematic-break"
    LINK_DEF = "link-target"
    MATH = "math"
    BLANK = "blank"
    #: A region a rewriter must pass through byte-for-byte: an mdd-managed
    #: export callout or footer, or a callout marker line such as ``> [!NOTE]``.
    #: Joining one into the paragraph below it changes what the file renders as.
    MANAGED = "managed-region"
    PROSE = "prose"


@dataclass(frozen=True)
class Line:
    """One classified source line.

    ``prefix`` is the leading bytes a rewriter must preserve verbatim — block
    quote markers, a list marker, the indent. ``cont_prefix`` is what a
    generated continuation line must start with so the block still parses.
    """

    number: int
    text: str
    cls: LineClass
    prefix: str = ""
    cont_prefix: str = ""
    masks: tuple[Span, ...] = ()
    links: tuple[LinkRef, ...] = ()
    block: int = -1
    hard_break: bool = False

    @property
    def content(self) -> str:
        """The line's text with its preserved prefix removed."""
        return self.text[len(self.prefix) :]


@dataclass(frozen=True)
class Classified:
    """A whole file's classification, plus the byte-level facts a writer needs."""

    lines: tuple[Line, ...]
    newline: str
    final_newline: bool


@dataclass(frozen=True)
class ClassifyError:
    """Why a file could not be classified.

    A value rather than an exception: one unparseable file must not end a
    corpus-wide run.
    """

    line: int
    reason: str


def split_lines(text: str) -> tuple[list[str], str, bool]:
    """Split *text* into lines, returning the dominant newline and whether one trails."""
    newline = "\r\n" if "\r\n" in text else "\n"
    final_newline = text.endswith(newline)
    body = text[: -len(newline)] if final_newline else text
    if not body and final_newline:
        return [], newline, True
    return body.split(newline), newline, final_newline


def join_lines(lines: list[str], newline: str, *, final_newline: bool) -> str:
    """Inverse of :func:`split_lines`."""
    body = newline.join(lines)
    return body + newline if final_newline else body


def _strip_quote(raw: str) -> tuple[str, str]:
    """Split *raw* into its block-quote prefix and the remainder."""
    match = _BQ.match(raw)
    if match is None or match.end() == 0:
        return "", raw
    return raw[: match.end()], raw[match.end() :]


def _indent_width(text: str) -> int:
    return len(_INDENT.match(text).group(0))  # pyright: ignore[reportOptionalMemberAccess]


def _hard_break(text: str) -> bool:
    return text.endswith(("  ", "\\")) and bool(text.strip())


@dataclass
class _State:
    """Mutable block-level scanner state."""

    in_frontmatter: bool = False
    fence: str | None = None
    in_comment: bool = False
    in_math: bool = False
    in_html_block: bool = False
    list_content_col: int | None = None
    after_blank: bool = True
    open_at: int = 0


def _prose_line(number: int, raw: str, quote: str, rest: str) -> Line:
    """Build a PROSE line, deriving the prefix and continuation prefix."""
    marker = _LIST.match(rest) or _FOOTNOTE_DEF.match(rest)
    if marker is not None:
        prefix = quote + marker.group(0)
        return Line(
            number=number,
            text=raw,
            cls=LineClass.PROSE,
            prefix=prefix,
            cont_prefix=quote + " " * (len(prefix) - len(quote)),
            hard_break=_hard_break(raw),
        )
    indent = " " * _indent_width(rest)
    return Line(
        number=number,
        text=raw,
        cls=LineClass.PROSE,
        prefix=quote + indent,
        cont_prefix=quote + indent,
        hard_break=_hard_break(raw),
    )


def _closes_fence(rest: str, fence: str) -> bool:
    closer = _FENCE.match(rest)
    return (
        closer is not None
        and closer.group(1)[0] == fence[0]
        and len(closer.group(1)) >= len(fence)
        and not rest[closer.end() :].strip()
    )


def _continuation(number: int, raw: str, rest: str, state: _State) -> Line | None:
    """Classify *raw* against an open multi-line construct, or return ``None``."""
    if state.in_frontmatter:
        state.in_frontmatter = rest.strip() not in ("---", "...")
        return Line(number, raw, LineClass.FRONTMATTER)
    if state.fence is not None:
        if _closes_fence(rest, state.fence):
            state.fence = None
        return Line(number, raw, LineClass.FENCED_CODE)
    if state.in_comment:
        state.in_comment = "-->" not in rest
        return Line(number, raw, LineClass.HTML_COMMENT)
    return _continuation_tail(number, raw, rest, state)


def _continuation_tail(number: int, raw: str, rest: str, state: _State) -> Line | None:
    """The second half of :func:`_continuation`: math blocks and HTML blocks."""
    if state.in_math:
        state.in_math = _MATH_FENCE.match(rest) is None
        return Line(number, raw, LineClass.MATH)
    if not state.in_html_block:
        return None
    if rest.strip():
        return Line(number, raw, LineClass.HTML_BLOCK)
    state.in_html_block = False
    return Line(number, raw, LineClass.BLANK)


def _open_block(number: int, raw: str, rest: str, state: _State) -> Line | None:
    """Classify *raw* as the opening line of a multi-line construct, or ``None``."""
    fence = _FENCE.match(rest)
    if fence is not None:
        state.fence = fence.group(1)
        state.open_at = number
        return Line(number, raw, LineClass.FENCED_CODE)
    stripped = rest.lstrip()
    if stripped.startswith("<!--"):
        if "-->" not in stripped[4:]:
            state.in_comment = True
            state.open_at = number
        return Line(number, raw, LineClass.HTML_COMMENT)
    if _MATH_FENCE.match(rest):
        if rest.strip() == "$$":
            state.in_math = True
            state.open_at = number
        return Line(number, raw, LineClass.MATH)
    if _HTML_BLOCK.match(rest):
        state.in_html_block = True
        return Line(number, raw, LineClass.HTML_BLOCK)
    return None


def _track_list(rest: str, state: _State) -> None:
    """Update the innermost open list item's content column."""
    marker = _LIST.match(rest) or _LIST_BARE.match(rest)
    if marker is not None:
        state.list_content_col = len(marker.group(0))
        return
    if rest.strip() and _indent_width(rest) == 0:
        state.list_content_col = None


def _is_indented_code(rest: str, state: _State) -> bool:
    """True when *rest* is an indented code block rather than a continuation line."""
    if not state.after_blank:
        return False
    indent = _indent_width(rest)
    floor = _INDENTED_CODE_COLUMN
    if state.list_content_col is not None:
        floor += state.list_content_col
    return indent >= floor


def _single_line_class(rest: str, state: _State) -> LineClass | None:
    """Return the class of a line that is a whole block by itself, or ``None``."""
    if _ATX.match(rest):
        return LineClass.HEADING
    if _TBREAK.match(rest):
        return LineClass.THEMATIC_BREAK
    if _is_indented_code(rest, state):
        return LineClass.INDENTED_CODE
    return LineClass.LINK_DEF if _LINK_DEF.match(rest) else None


def _classify_fresh(number: int, raw: str, quote: str, rest: str, state: _State) -> Line:
    """Classify a line that is not inside any open multi-line construct."""
    opened = _open_block(number, raw, rest, state)
    if opened is not None:
        return opened
    single = _single_line_class(rest, state)
    if single is not None:
        return Line(number, raw, single)
    _track_list(rest, state)
    if not rest.strip():
        return Line(number, raw, LineClass.BLOCK_QUOTE if quote else LineClass.BLANK)
    return _prose_line(number, raw, quote, rest)


def _scan_blocks(raw_lines: list[str]) -> tuple[list[Line], ClassifyError | None]:
    """Run the block-level state machine over *raw_lines*."""
    state = _State()
    out: list[Line] = []
    for index, raw in enumerate(raw_lines):
        number = index + 1
        if number == 1 and raw.rstrip() == "---":
            state.in_frontmatter = True
            state.open_at = 1
            out.append(Line(1, raw, LineClass.FRONTMATTER))
            continue
        quote, rest = _strip_quote(raw)
        line = _continuation(number, raw, rest, state) or _classify_fresh(
            number, raw, quote, rest, state
        )
        state.after_blank = line.cls in (LineClass.BLANK, LineClass.BLOCK_QUOTE)
        out.append(line)
    if state.in_frontmatter:
        return out, ClassifyError(state.open_at, "frontmatter block never closes")
    if state.fence is not None:
        return out, ClassifyError(state.open_at, "fenced code block never closes")
    if state.in_comment:
        return out, ClassifyError(state.open_at, "HTML comment never closes")
    if state.in_math:
        return out, ClassifyError(state.open_at, "math block never closes")
    return out, None


def _apply_setext(lines: list[Line]) -> None:
    """Reclassify a paragraph followed by an ``===``/``---`` rule as a heading."""
    for index, line in enumerate(lines):
        if index == 0 or line.cls not in (LineClass.PROSE, LineClass.THEMATIC_BREAK):
            continue
        _, rest = _strip_quote(line.text)
        if not _SETEXT.match(rest) or lines[index - 1].cls is not LineClass.PROSE:
            continue
        lines[index] = replace(line, cls=LineClass.HEADING, prefix="", cont_prefix="")
        back = index - 1
        while back >= 0 and lines[back].cls is LineClass.PROSE:
            lines[back] = replace(lines[back], cls=LineClass.HEADING, prefix="", cont_prefix="")
            back -= 1


def _apply_tables(lines: list[Line]) -> None:
    """Reclassify a header row, its delimiter row and the body rows as a table."""
    for index, line in enumerate(lines):
        _, rest = _strip_quote(line.text)
        if index == 0 or not _DELIM_ROW.match(rest) or "|" not in rest:
            continue
        header = lines[index - 1]
        if header.cls is not LineClass.PROSE or "|" not in header.text:
            continue
        lines[index - 1] = replace(header, cls=LineClass.TABLE, prefix="", cont_prefix="")
        lines[index] = replace(line, cls=LineClass.TABLE, prefix="", cont_prefix="")
        forward = index + 1
        while (
            forward < len(lines)
            and lines[forward].cls is LineClass.PROSE
            and "|" in lines[forward].text
        ):
            lines[forward] = replace(lines[forward], cls=LineClass.TABLE, prefix="", cont_prefix="")
            forward += 1


def _mark_managed(lines: list[Line], index: int) -> None:
    lines[index] = replace(lines[index], cls=LineClass.MANAGED, prefix="", cont_prefix="")


def _apply_managed(lines: list[Line]) -> None:
    """Reclassify mdd-managed export callouts, the mdd footer, and callout markers.

    These are matched on export and stripped before a push, so a reflow that
    reshaped one could push it into the page body.
    """
    for index, line in enumerate(lines):
        if line.cls not in (LineClass.PROSE, LineClass.BLOCK_QUOTE):
            continue
        quote, rest = _strip_quote(line.text)
        if not quote:
            continue
        content = rest.strip()
        if _ALERT_MARKER.match(content):
            _mark_managed(lines, index)
            continue
        if not _MANAGED_CALLOUT.match(content) and not _MDD_FOOTER.match(content):
            continue
        forward = index
        while forward < len(lines) and _strip_quote(lines[forward].text)[0]:
            _mark_managed(lines, forward)
            forward += 1


def _assign_blocks(lines: list[Line]) -> None:
    """Group contiguous prose lines that belong to the same logical paragraph."""
    previous: Line | None = None
    counter = 0
    for index, line in enumerate(lines):
        if line.cls is not LineClass.PROSE:
            previous = None
            continue
        if previous is not None and previous.cont_prefix == line.prefix:
            block = previous.block
        else:
            counter += 1
            block = counter
        lines[index] = replace(line, block=block)
        previous = lines[index]


_UNMASKED_CLASSES = (LineClass.FRONTMATTER, LineClass.FENCED_CODE, LineClass.INDENTED_CODE)


def block_text(lines: Sequence[Line]) -> tuple[str, list[int]]:
    """Unwrap a prose block to one logical string, plus each line's start offset.

    Masking must run over this string rather than per line: a hard-wrapped
    paragraph can split a code span or a link across a soft break, and a
    per-line scan sees two unbalanced halves instead of one construct.
    """
    starts: list[int] = []
    parts: list[str] = []
    position = 0
    for line in lines:
        if parts:
            position += 1
        starts.append(position)
        content = line.text[len(line.prefix) :].rstrip()
        parts.append(content)
        position += len(content)
    return " ".join(parts), starts


@dataclass(frozen=True)
class _Bound:
    """Where one line of a block sits within the block's joined text."""

    index: int
    start: int
    length: int
    shift: int

    def clip(self, span: Span) -> Span | None:
        low, high = max(span.start, self.start), min(span.end, self.start + self.length)
        return Span(low + self.shift, high + self.shift, span.cls) if low < high else None

    def holds(self, position: int) -> bool:
        return self.start <= position < self.start + self.length


def _block_bounds(lines: Sequence[Line], indices: Sequence[int]) -> list[_Bound]:
    block = [lines[index] for index in indices]
    _, starts = block_text(block)
    return [
        _Bound(
            index=index,
            start=starts[offset],
            length=len(block[offset].content.rstrip()),
            shift=len(block[offset].prefix) - starts[offset],
        )
        for offset, index in enumerate(indices)
    ]


def _spread_masks(lines: list[Line], indices: Sequence[int]) -> None:
    """Scan one block's joined text and project the spans back onto its lines."""
    joined, _ = block_text([lines[index] for index in indices])
    result = scan(joined)
    for bound in _block_bounds(lines, indices):
        spans = [clipped for span in result.masks if (clipped := bound.clip(span)) is not None]
        links = [
            LinkRef(ref.start + bound.shift, ref.target)
            for ref in result.links
            if bound.holds(ref.start)
        ]
        lines[bound.index] = replace(lines[bound.index], masks=tuple(spans), links=tuple(links))


def _apply_masks(lines: list[Line]) -> None:
    """Mask inline constructs: per block for prose, per line for everything else."""
    blocks: dict[int, list[int]] = {}
    for index, line in enumerate(lines):
        if line.cls is LineClass.PROSE:
            blocks.setdefault(line.block, []).append(index)
        elif line.cls not in _UNMASKED_CLASSES:
            result = scan(line.text, start=len(line.prefix))
            lines[index] = replace(line, masks=result.masks, links=result.links)
    for indices in blocks.values():
        _spread_masks(lines, indices)


def classify(text: str) -> Classified | ClassifyError:
    """Classify *text* line by line, or explain why it cannot be classified."""
    raw_lines, newline, final_newline = split_lines(text)
    lines, error = _scan_blocks(raw_lines)
    if error is not None:
        return error
    _apply_setext(lines)
    _apply_tables(lines)
    _apply_managed(lines)
    _assign_blocks(lines)
    _apply_masks(lines)
    return Classified(lines=tuple(lines), newline=newline, final_newline=final_newline)
