"""AI-powered markdown rewrite with protected-region pipeline.

Usage::

    from mdd.ai.rewrite import rewrite_file, RewriteResult

    result = rewrite_file(
        path=Path("docs/my-page.md"),
        client=client,
        style_path=None,   # use bundled default
        apply=False,       # write <file>.rewrite.md sibling
    )
    print(result.status)  # "rewritten" | "cached" | "error"
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml  # pyright: ignore[reportMissingModuleSource]

from mdd.utils.logging import get_logger

if TYPE_CHECKING:
    from mdd.ai.client import Client

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Protected-region pipeline
# ---------------------------------------------------------------------------

# Placeholder format: unique enough to survive model paraphrasing of prose.
_PLACEHOLDER_PREFIX = "__MDD_PROTECTED_"
_PLACEHOLDER_SUFFIX = "__"

# Patterns that mark protected regions, in priority order.
# Each entry is (name, compiled_regex).  The regex must capture the full
# protected span (possibly multi-line).
#
# Order matters for overlapping patterns: frontmatter first, then fenced
# blocks (longest-first among opening fences), then tables.
_PROTECTED_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    # YAML frontmatter at the very start of the file
    (
        "frontmatter",
        re.compile(r"\A---\n.*?\n---\n?", re.DOTALL),
    ),
    # Fenced code / raw blocks with any info string (``` or ~~~, 3+ chars)
    # including {=confluence}, {=html}, etc.
    (
        "fenced",
        re.compile(r"(?m)^(`{3,}|~{3,})[^\n]*\n.*?\n\1[ \t]*$", re.DOTALL),
    ),
    # Confluence export header: the blockquote that starts a Confluence export
    # ("> **Confluence export …" up to the next blank line or heading)
    (
        "export_header",
        re.compile(
            r"(?m)^> \*\*Confluence export[^\n]*\n(?:>[^\n]*\n)*",
            re.DOTALL,
        ),
    ),
    # MDD footer: the blockquote that ends with MDD-generated content marker
    # ("> *Generated by mdd …" at the end of the file)
    (
        "mdd_footer",
        re.compile(
            r"(?m)^> \*Generated by mdd[^\n]*\n?$",
            re.DOTALL,
        ),
    ),
    # Markdown tables: lines where every non-empty line begins with |
    # A table block is the contiguous run of pipe-lines.
    (
        "table",
        re.compile(r"(?m)(?:^\|[^\n]*\n)+"),
    ),
]


@dataclass
class _Region:
    placeholder: str
    original: str


def extract_protected(text: str) -> tuple[str, list[_Region]]:
    """Replace protected regions in *text* with sequential placeholder tokens.

    Returns the transformed text and the list of replaced regions in order.
    Protected regions are guaranteed to round-trip byte-identically.
    """
    regions: list[_Region] = []
    idx = 0
    result_parts: list[str] = []
    pos = 0  # current scan position

    while pos < len(text):
        earliest_match: re.Match[str] | None = None
        earliest_start = len(text)

        for _name, pattern in _PROTECTED_PATTERNS:
            m = pattern.search(text, pos)
            if m and m.start() < earliest_start:
                earliest_match = m
                earliest_start = m.start()

        if earliest_match is None:
            # No more protected regions — append the rest.
            result_parts.append(text[pos:])
            break

        # Append text before the match.
        result_parts.append(text[pos : earliest_match.start()])

        placeholder = f"{_PLACEHOLDER_PREFIX}{idx}{_PLACEHOLDER_SUFFIX}"
        regions.append(_Region(placeholder=placeholder, original=earliest_match.group()))
        result_parts.append(placeholder)
        idx += 1
        pos = earliest_match.end()

    return "".join(result_parts), regions


def stitch_protected(text: str, regions: list[_Region]) -> str:
    """Replace placeholder tokens back with their original protected content.

    Raises ValueError if any placeholder is missing from *text*.
    """
    for region in regions:
        if region.placeholder not in text:
            raise ValueError(
                f"Protected-region placeholder {region.placeholder!r} is missing from "
                "the model's output. The model likely removed or rewrote a protected "
                "block. Refusing to produce output — the rewrite is unsafe."
            )
        text = text.replace(region.placeholder, region.original, 1)
    return text


# ---------------------------------------------------------------------------
# Prompt loading
# ---------------------------------------------------------------------------


def _default_tone_path() -> Path:
    """Return the path to the bundled default tone-of-voice prompt.

    Users can override this via ``--style <path>`` to swap in their own
    voice. The constraints block (placeholder preservation, pass-through
    rules) is always composed on top — see :func:`_load_constraints` and
    :func:`_compose_system_prompt`.
    """
    return Path(__file__).parent / "prompts" / "tone-of-voice.md"


def _constraints_path() -> Path:
    """Return the path to the bundled rewrite-constraints prompt.

    This block carries the load-bearing rules (preserve placeholder tokens,
    do not alter substance, return only the rewritten body) and is NEVER
    overridable — ``--style`` only swaps the tone block.
    """
    return Path(__file__).parent / "prompts" / "rewrite-constraints.md"


def _load_tone(path: Path | None) -> tuple[str, bytes]:
    """Load the tone-of-voice prompt and return (text, sha256_digest).

    *path* is None → use the bundled default.
    """
    resolved = path if path is not None else _default_tone_path()
    text = resolved.read_text(encoding="utf-8")
    digest = hashlib.sha256(text.encode()).digest()
    return text, digest


def _load_constraints() -> tuple[str, bytes]:
    """Load the immutable constraints prompt and return (text, sha256_digest)."""
    text = _constraints_path().read_text(encoding="utf-8")
    digest = hashlib.sha256(text.encode()).digest()
    return text, digest


def _compose_system_prompt(tone_text: str, constraints_text: str) -> str:
    """Compose the rewrite system prompt as ``tone\\n\\n---\\n\\n{constraints}``.

    The constraints block always lands after the tone block so a model that
    pays more attention to the trailing instructions still respects the
    placeholder-preservation rules.
    """
    return f"{tone_text.rstrip()}\n\n---\n\n{constraints_text.lstrip()}"


# ---------------------------------------------------------------------------
# Body extraction (strip frontmatter for model input)
# ---------------------------------------------------------------------------


def _split_frontmatter(text: str) -> tuple[str, str]:
    """Split *text* into (frontmatter_block, body).

    *frontmatter_block* includes the ``---\\n...\\n---\\n`` delimiters, or is
    empty if no frontmatter is present.  *body* is the remainder.
    """
    if not (text.startswith(("---\n", "---\r\n"))):
        return "", text

    rest = text[4:]
    end_idx = rest.find("\n---\n")
    if end_idx == -1:
        if rest.endswith("\n---"):
            end_idx = len(rest) - 4
            return text[: 4 + end_idx + 4], rest[end_idx + 4 :]
        return "", text

    fm_end = 4 + end_idx + 5  # "---\n" + yaml + "\n---\n"
    return text[:fm_end], text[fm_end:]


def _restore_boundary_whitespace(original_body: str, new_body: str) -> str:
    """Re-attach *original_body*'s leading/trailing whitespace to *new_body*.

    The model routinely trims the blank line that follows the frontmatter
    delimiter or drops the trailing newline, producing whitespace-only diffs
    against the source.  We keep only the model's interior content and restore
    the source body's exact leading and trailing whitespace, so boundary
    whitespace never churns.
    """
    core = new_body.strip()
    if not core:
        # Model returned only whitespace; keep the source body verbatim.
        return original_body
    leading = original_body[: len(original_body) - len(original_body.lstrip())]
    trailing = original_body[len(original_body.rstrip()) :]
    return leading + core + trailing


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass
class RewriteResult:
    """Result of rewriting one file."""

    path: Path
    status: str  # "rewritten" | "cached" | "error"
    output_path: Path | None = None
    error: str | None = None
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_usd: float | None = None


def _check_managed_for_apply(path: Path, full_text: str) -> bool:  # noqa: ARG001
    """Return True if the file's frontmatter indicates a managed-elsewhere page.

    Checks ``confluence.managed_by`` in the frontmatter (stamped by the
    pull-side logic).  Does not make any HTTP calls.
    """
    try:
        if not (full_text.startswith(("---\n", "---\r\n"))):
            return False
        rest = full_text[4:]
        end_idx = rest.find("\n---\n")
        if end_idx == -1:
            return False
        yaml_block = rest[:end_idx]
        fm_raw: Any = yaml.safe_load(yaml_block)  # pyright: ignore[reportAny]
        if not isinstance(fm_raw, dict):
            return False
        fm: dict[str, Any] = fm_raw  # pyright: ignore[reportUnknownVariableType]
        conf_raw: Any = fm.get("confluence")  # pyright: ignore[reportAny]
        if not isinstance(conf_raw, dict):
            return False
        conf: dict[str, Any] = conf_raw  # pyright: ignore[reportUnknownVariableType]
        managed_by: Any = conf.get("managed_by")  # pyright: ignore[reportAny]
        return bool(managed_by)
    except Exception:
        return False


def rewrite_file(  # noqa: C901, PLR0911, PLR0912, PLR0915
    path: Path,
    client: Client,
    *,
    style_path: Path | None = None,
    apply: bool = False,
    model: str | None = None,
) -> RewriteResult:
    """Rewrite a single markdown file via the AI client.

    Parameters
    ----------
    path:
        The source markdown file.
    client:
        An initialised ``mdd.ai.Client`` instance.
    style_path:
        Override the default tone-of-voice prompt file.  ``None`` → bundled
        default.
    apply:
        If ``True``, overwrite *path* in place (atomic tmp→rename).
        If ``False``, write a ``<path>.rewrite.md`` sibling.
    model:
        Override the model selection.  ``None`` → use ``task="default"``
        from the client config.

    Returns
    -------
    RewriteResult
    """
    if not path.exists():
        return RewriteResult(
            path=path,
            status="error",
            error=f"File not found: {path}",
        )

    try:
        full_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return RewriteResult(path=path, status="error", error=str(exc))

    try:
        tone_text, tone_digest = _load_tone(style_path)
    except OSError as exc:
        return RewriteResult(path=path, status="error", error=f"Cannot read style file: {exc}")

    try:
        constraints_text, constraints_digest = _load_constraints()
    except OSError as exc:
        return RewriteResult(
            path=path,
            status="error",
            error=f"Cannot read constraints prompt: {exc}",
        )

    system_prompt = _compose_system_prompt(tone_text, constraints_text)

    # Split off frontmatter so it is not sent to the model.
    frontmatter_block, body = _split_frontmatter(full_text)

    # Compute the body hash for the cache key.
    body_hash = hashlib.sha256(body.encode()).digest()

    # Extract protected regions from the body.
    transformed_body, regions = extract_protected(body)

    # Cache key extra: body + tone + constraints. Constraints digest is
    # included so a bundled-prompt upgrade invalidates stale rewrites.
    cache_key_extra = body_hash + tone_digest + constraints_digest

    try:
        result = client.chat(
            system=system_prompt,
            user=transformed_body,
            task="default",
            model=model,
            cache_key_extra=cache_key_extra,
        )
    except Exception as exc:
        return RewriteResult(path=path, status="error", error=str(exc))

    # Stitch protected regions back.
    try:
        rewritten_body = stitch_protected(result.text, regions)
    except ValueError as exc:
        return RewriteResult(path=path, status="error", error=str(exc))

    # Restore the source body's boundary whitespace to avoid whitespace-only churn.
    rewritten_body = _restore_boundary_whitespace(body, rewritten_body)

    rewritten_full = frontmatter_block + rewritten_body

    # When --apply is set, check for managed-elsewhere before overwriting.
    if apply:
        try:
            _apply_blocked = _check_managed_for_apply(path, full_text)
        except Exception:
            _apply_blocked = False
        if _apply_blocked:
            # Refuse apply but still emit the candidate sibling.
            out_path = path.parent / (path.name + ".rewrite.md")
            tmp_path = out_path.with_suffix(out_path.suffix + ".tmp")
            try:
                tmp_path.write_text(rewritten_full, encoding="utf-8")
                tmp_path.replace(out_path)
            except OSError as exc:
                tmp_path.unlink(missing_ok=True)
                return RewriteResult(path=path, status="error", error=f"Write failed: {exc}")
            return RewriteResult(
                path=path,
                status="error",
                error=(
                    f"Managed-elsewhere page: --apply refused. Candidate written to {out_path}."
                ),
                output_path=out_path,
                prompt_tokens=result.prompt_tokens,
                completion_tokens=result.completion_tokens,
                cost_usd=result.cost_usd,
            )

    # Determine output path and write atomically.
    if apply:
        out_path = path
        tmp_path = path.with_suffix(path.suffix + ".tmp")
    else:
        out_path = path.parent / (path.name + ".rewrite.md")
        tmp_path = out_path.with_suffix(out_path.suffix + ".tmp")

    try:
        tmp_path.write_text(rewritten_full, encoding="utf-8")
        tmp_path.replace(out_path)
    except OSError as exc:
        tmp_path.unlink(missing_ok=True)
        return RewriteResult(path=path, status="error", error=f"Write failed: {exc}")

    return RewriteResult(
        path=path,
        status="cached" if result.cached else "rewritten",
        output_path=out_path,
        prompt_tokens=result.prompt_tokens,
        completion_tokens=result.completion_tokens,
        cost_usd=result.cost_usd,
    )


def rewrite_files(
    paths: list[Path],
    client: Client,
    *,
    style_path: Path | None = None,
    apply: bool = False,
    model: str | None = None,
) -> list[RewriteResult]:
    """Rewrite multiple files serially; there is deliberately no parallelism.

    Returns the list of results in the same order as *paths*.
    """
    results: list[RewriteResult] = []
    for p in paths:
        result = rewrite_file(p, client, style_path=style_path, apply=apply, model=model)
        results.append(result)
        _print_file_result(result)
    return results


def _print_file_result(result: RewriteResult) -> None:
    if result.status == "error":
        log.error("  error:    %s  — %s", result.path, result.error)
    elif result.status == "cached":
        log.info("  cached:   %s", result.path)
    else:
        log.info("  rewritten:%s  →  %s", result.path, result.output_path)


def print_run_summary(results: list[RewriteResult], client: Client) -> None:
    """Log a concise end-of-run summary."""
    cached = sum(1 for r in results if r.status == "cached")
    rewritten = sum(1 for r in results if r.status == "rewritten")
    errors = sum(1 for r in results if r.status == "error")
    summary = client.summary
    log.info(
        "Rewrite summary: %d rewritten, %d cached, %d error(s).",
        rewritten,
        cached,
        errors,
    )
    if summary.api_calls > 0:
        tokens = summary.prompt_tokens + summary.completion_tokens
        log.info(
            "  Tokens used: %s (prompt=%s, completion=%s)",
            f"{tokens:,}",
            f"{summary.prompt_tokens:,}",
            f"{summary.completion_tokens:,}",
        )
        if summary.cost_usd > 0:
            log.info("  Estimated cost: $%.4f", summary.cost_usd)
