"""Tests for mdd.ai.rewrite — protected-region pipeline and rewrite logic (spec S21)."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

import pytest

from mdd.ai.models import ChatResult
from mdd.ai.rewrite import (
    _compose_system_prompt as _compose_system_prompt,  # pyright: ignore[reportPrivateUsage]
)
from mdd.ai.rewrite import (
    _default_tone_path as _default_tone_path,  # pyright: ignore[reportPrivateUsage]
)
from mdd.ai.rewrite import (
    _load_constraints as _load_constraints,  # pyright: ignore[reportPrivateUsage]
)
from mdd.ai.rewrite import _load_tone as _load_tone  # pyright: ignore[reportPrivateUsage]
from mdd.ai.rewrite import (
    _split_frontmatter as _split_frontmatter,  # pyright: ignore[reportPrivateUsage]
)
from mdd.ai.rewrite import extract_protected, rewrite_file, rewrite_files, stitch_protected

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _make_chat_result(text: str, cached: bool = False) -> ChatResult:
    return ChatResult(
        text=text,
        cached=cached,
        prompt_tokens=10,
        completion_tokens=5,
        cost_usd=None,
    )


def _make_mock_client(return_text: str, cached: bool = False) -> MagicMock:
    """Return a mock Client whose chat() returns the given text."""
    mock = MagicMock()
    mock.chat.return_value = _make_chat_result(return_text, cached=cached)
    mock.summary.api_calls = 1
    mock.summary.prompt_tokens = 10
    mock.summary.completion_tokens = 5
    mock.summary.cost_usd = 0.0
    return mock


# ---------------------------------------------------------------------------
# extract_protected / stitch_protected
# ---------------------------------------------------------------------------


class TestProtectedRegionPipeline:
    def test_no_protected_regions(self) -> None:
        text = "Hello world.\n\nSome more text."
        transformed, regions = extract_protected(text)
        assert transformed == text
        assert regions == []

    def test_frontmatter_extracted(self) -> None:
        text = "---\ntitle: Test\n---\n\nBody text here."
        transformed, regions = extract_protected(text)
        assert "---\ntitle: Test\n---\n" in regions[0].original
        assert "__MDD_PROTECTED_0__" in transformed
        assert "Body text here." in transformed

    def test_code_block_extracted(self) -> None:
        text = "Before\n\n```python\nx = 1\n```\n\nAfter"
        transformed, _regions = extract_protected(text)
        assert "```python" not in transformed
        assert "__MDD_PROTECTED_0__" in transformed
        assert "Before" in transformed
        assert "After" in transformed

    def test_fenced_confluence_block_extracted(self) -> None:
        text = "Prose\n\n```{=confluence}\n<ac:macro/>\n```\n\nMore prose"
        transformed, regions = extract_protected(text)
        assert "{=confluence}" not in transformed
        assert len(regions) == 1
        assert "{=confluence}" in regions[0].original

    def test_fenced_html_block_extracted(self) -> None:
        text = "Prose\n\n```{=html}\n<div>test</div>\n```\n\nMore"
        transformed, regions = extract_protected(text)
        assert "{=html}" not in transformed
        assert len(regions) == 1

    def test_table_extracted(self) -> None:
        table = "| A | B |\n|---|---|\n| 1 | 2 |\n"
        text = f"Before\n\n{table}\nAfter"
        transformed, regions = extract_protected(text)
        assert "| A |" not in transformed
        assert len(regions) == 1
        assert "| A |" in regions[0].original

    def test_confluence_export_header_extracted(self) -> None:
        header = "> **Confluence export** — Auto-generated.\n> Source: https://example.com\n"
        text = f"{header}\n# Title\n\nBody"
        transformed, regions = extract_protected(text)
        assert "> **Confluence export**" not in transformed
        assert len(regions) == 1
        assert "> **Confluence export**" in regions[0].original

    def test_mdd_footer_extracted(self) -> None:
        footer = "> *Generated by mdd — https://github.com/schubergphilis/mdd*\n"
        text = f"Body text\n\n{footer}"
        transformed, regions = extract_protected(text)
        assert "> *Generated by mdd" not in transformed
        assert len(regions) == 1
        assert "> *Generated by mdd" in regions[0].original

    def test_multiple_protected_regions(self) -> None:
        text = "```python\nx=1\n```\n\nProse middle\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\nEnd"
        transformed, regions = extract_protected(text)
        assert len(regions) == 2
        assert "__MDD_PROTECTED_0__" in transformed
        assert "__MDD_PROTECTED_1__" in transformed
        assert "Prose middle" in transformed
        assert "End" in transformed

    def test_round_trip_preserves_content(self) -> None:
        """Extract → uppercase prose (model stub) → stitch → identical protected content."""
        text = (
            "---\ntitle: Doc\n---\n\n"
            "This is prose.\n\n"
            "```python\nx = 42\n```\n\n"
            "More prose.\n\n"
            "| H1 | H2 |\n|----|----|\n| a  | b  |\n"
        )
        transformed, regions = extract_protected(text)

        # Simulate a model that uppercases all text (but leaves placeholders alone).
        def uppercase_non_placeholder(t: str) -> str:
            import re

            parts = re.split(r"(__MDD_PROTECTED_\d+__)", t)
            return "".join(p if p.startswith("__MDD_PROTECTED_") else p.upper() for p in parts)

        model_output = uppercase_non_placeholder(transformed)
        result = stitch_protected(model_output, regions)

        # Protected regions must be byte-identical.
        assert "---\ntitle: Doc\n---\n" in result
        assert "```python\nx = 42\n```" in result
        assert "| H1 | H2 |" in result

    def test_stitch_raises_on_missing_placeholder(self) -> None:
        text = "Prose\n\n```code\ncontent\n```\n\nMore"
        _, regions = extract_protected(text)
        # Simulate model that dropped the placeholder
        bad_output = "PROSE\n\nMORE"
        with pytest.raises(ValueError, match="missing from the model"):
            stitch_protected(bad_output, regions)

    def test_full_protected_fixture(self) -> None:
        """All protected types in the fixture file round-trip correctly."""
        content = (FIXTURES_DIR / "protected.md").read_text(encoding="utf-8")
        transformed, regions = extract_protected(content)

        # Simulate a model that returns the transformed text as-is (identity).
        result = stitch_protected(transformed, regions)
        assert result == content

    def test_tilde_fenced_block_extracted(self) -> None:
        text = "Before\n\n~~~\nsome content\n~~~\n\nAfter"
        transformed, regions = extract_protected(text)
        assert "~~~" not in transformed
        assert len(regions) == 1


# ---------------------------------------------------------------------------
# _split_frontmatter
# ---------------------------------------------------------------------------


class TestSplitFrontmatter:
    def test_no_frontmatter(self) -> None:
        body = "# Title\n\nContent"
        fm, b = _split_frontmatter(body)
        assert fm == ""
        assert b == body

    def test_with_frontmatter(self) -> None:
        text = "---\ntitle: Test\n---\n\n# Body"
        fm, b = _split_frontmatter(text)
        assert fm == "---\ntitle: Test\n---\n"
        assert b == "\n# Body"

    def test_frontmatter_not_sent_to_model(self) -> None:
        """The frontmatter block must NOT appear in the body sent to the model."""
        text = "---\ntitle: Secret\nauthor: Alice\n---\n\nBody here."
        _fm, b = _split_frontmatter(text)
        assert "title: Secret" not in b
        assert "Body here." in b


# ---------------------------------------------------------------------------
# _load_tone / _load_constraints / _compose_system_prompt
# ---------------------------------------------------------------------------


class TestLoadTone:
    def test_default_tone_exists(self) -> None:
        path = _default_tone_path()
        assert path.exists(), f"Default tone prompt not found: {path}"

    def test_default_tone_returns_digest(self) -> None:
        text, digest = _load_tone(None)
        assert isinstance(text, str)
        assert len(text) > 0
        assert isinstance(digest, bytes)
        assert len(digest) == 32  # SHA-256

    def test_custom_tone(self, tmp_path: Path) -> None:
        style_file = tmp_path / "my-style.md"
        style_file.write_text("Be very concise.", encoding="utf-8")
        text, digest = _load_tone(style_file)
        assert text == "Be very concise."
        expected_digest = hashlib.sha256(b"Be very concise.").digest()
        assert digest == expected_digest

    def test_different_tones_produce_different_digests(self, tmp_path: Path) -> None:
        a = tmp_path / "a.md"
        b = tmp_path / "b.md"
        a.write_text("Style A", encoding="utf-8")
        b.write_text("Style B", encoding="utf-8")
        _, da = _load_tone(a)
        _, db = _load_tone(b)
        assert da != db


class TestLoadConstraints:
    def test_constraints_file_exists(self) -> None:
        text, digest = _load_constraints()
        assert isinstance(text, str)
        assert len(text) > 0
        assert isinstance(digest, bytes)
        assert len(digest) == 32

    def test_constraints_mention_placeholder_preservation(self) -> None:
        text, _ = _load_constraints()
        # The load-bearing instruction must be present — this is the
        # whole point of splitting the prompt: --style cannot drop it.
        assert "placeholder" in text.lower()


class TestComposeSystemPrompt:
    def test_combines_tone_and_constraints(self) -> None:
        composed = _compose_system_prompt("TONE_BLOCK", "CONSTRAINTS_BLOCK")
        assert "TONE_BLOCK" in composed
        assert "CONSTRAINTS_BLOCK" in composed
        # Constraints come AFTER tone so they're the trailing instructions.
        assert composed.index("TONE_BLOCK") < composed.index("CONSTRAINTS_BLOCK")

    def test_custom_tone_preserves_bundled_constraints(self) -> None:
        constraints_text, _ = _load_constraints()
        composed = _compose_system_prompt("Be terse.", constraints_text)
        # The user-supplied tone cannot drop the placeholder rule.
        assert "placeholder" in composed.lower()


# ---------------------------------------------------------------------------
# rewrite_file
# ---------------------------------------------------------------------------


class TestRewriteFile:
    def test_produces_sibling_by_default(self, tmp_path: Path) -> None:
        src = tmp_path / "page.md"
        src.write_text("# Hello\n\nSome text.\n", encoding="utf-8")

        mock_client = _make_mock_client("# Hello\n\nRewritten text.\n")

        result = rewrite_file(src, mock_client)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        assert result.output_path == tmp_path / "page.md.rewrite.md"
        assert result.output_path is not None
        assert result.output_path.exists()
        assert "Rewritten text." in result.output_path.read_text()

    def test_apply_overwrites_in_place(self, tmp_path: Path) -> None:
        src = tmp_path / "page.md"
        src.write_text("# Hello\n\nOriginal text.\n", encoding="utf-8")

        mock_client = _make_mock_client("# Hello\n\nApplied text.\n")

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        assert result.output_path == src
        assert "Applied text." in src.read_text()

    def test_frontmatter_preserved_byte_identical(self, tmp_path: Path) -> None:
        fm = "---\ntitle: Test\nconfluence:\n  page_id: '123'\n---\n"
        body = "\n# Body\n\nSome prose.\n"
        src = tmp_path / "page.md"
        src.write_text(fm + body, encoding="utf-8")

        # Model returns only the body (no frontmatter in model output).
        mock_client = _make_mock_client("# Body\n\nRewritten prose.\n")

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        content = src.read_text()
        assert content.startswith(fm)

    def test_boundary_whitespace_restored(self, tmp_path: Path) -> None:
        # Source has a blank line after the frontmatter and trailing blank lines.
        fm = "---\ntitle: Test\n---\n"
        body = "\n> Header\n\n# Title\n\n{{confluence:children}}\n\n  \n\n"
        src = tmp_path / "page.md"
        src.write_text(fm + body, encoding="utf-8")

        # Model trims the leading blank line and all trailing whitespace.
        mock_client = _make_mock_client("> Header\n\n# Title\n\n{{confluence:children}}")

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        # Boundary whitespace matches the source exactly — no churn.
        assert src.read_text(encoding="utf-8") == fm + body

    def test_boundary_whitespace_only_whitespace_body_preserved(self, tmp_path: Path) -> None:
        body = "\n\n  \n"
        src = tmp_path / "page.md"
        src.write_text(body, encoding="utf-8")

        mock_client = _make_mock_client("   \n")

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        assert src.read_text(encoding="utf-8") == body

    def test_missing_placeholder_returns_error(self, tmp_path: Path) -> None:
        src = tmp_path / "page.md"
        src.write_text("Some prose.\n\n```python\nx=1\n```\n\nMore prose.\n", encoding="utf-8")

        # Model drops the placeholder.
        mock_client = _make_mock_client("Some prose. More prose.")

        result = rewrite_file(src, mock_client)  # pyright: ignore[reportArgumentType]

        assert result.status == "error"
        assert "missing" in (result.error or "").lower()

    def test_cache_hit_returns_cached_status(self, tmp_path: Path) -> None:
        src = tmp_path / "page.md"
        src.write_text("# Hello\n\nSome text.\n", encoding="utf-8")

        mock_client = _make_mock_client("# Hello\n\nCached text.\n", cached=True)

        result = rewrite_file(src, mock_client)  # pyright: ignore[reportArgumentType]

        assert result.status == "cached"

    def test_file_not_found_returns_error(self, tmp_path: Path) -> None:
        src = tmp_path / "nonexistent.md"
        mock_client = MagicMock()

        result = rewrite_file(src, mock_client)  # pyright: ignore[reportArgumentType]

        assert result.status == "error"
        assert "not found" in (result.error or "").lower()

    def test_style_hash_used_in_cache_key(self, tmp_path: Path) -> None:
        """Different style files must produce different cache keys."""
        src = tmp_path / "page.md"
        src.write_text("# Hello\n\nText.\n", encoding="utf-8")

        style_a = tmp_path / "style_a.md"
        style_b = tmp_path / "style_b.md"
        style_a.write_text("Style A", encoding="utf-8")
        style_b.write_text("Style B", encoding="utf-8")

        call_extras: list[bytes] = []

        def capture_chat(**kwargs: Any) -> ChatResult:  # pyright: ignore[reportAny]
            call_extras.append(kwargs.get("cache_key_extra", b""))
            return _make_chat_result("# Hello\n\nResult.\n")

        mock_client = MagicMock()
        mock_client.chat.side_effect = capture_chat
        mock_client.summary.api_calls = 0
        mock_client.summary.prompt_tokens = 0
        mock_client.summary.completion_tokens = 0
        mock_client.summary.cost_usd = 0.0

        rewrite_file(src, mock_client, style_path=style_a)  # pyright: ignore[reportArgumentType]
        rewrite_file(src, mock_client, style_path=style_b)  # pyright: ignore[reportArgumentType]

        assert len(call_extras) == 2
        assert call_extras[0] != call_extras[1]

    def test_code_block_preserved_through_rewrite(self, tmp_path: Path) -> None:
        """Protected code blocks must be byte-identical after rewrite."""
        code_block = "```python\ndef my_func():\n    return 42\n```"
        src = tmp_path / "page.md"
        src.write_text(f"Intro prose.\n\n{code_block}\n\nOutro prose.\n", encoding="utf-8")

        # Model returns transformed prose with placeholder preserved
        def identity_model(**kwargs: Any) -> ChatResult:  # pyright: ignore[reportAny]
            user_text: str = kwargs["user"]
            # Replace non-placeholder text with uppercase, leave placeholder.
            import re

            parts = re.split(r"(__MDD_PROTECTED_\d+__)", user_text)
            out = "".join(p if p.startswith("__MDD_PROTECTED_") else p.upper() for p in parts)
            return _make_chat_result(out)

        mock_client = MagicMock()
        mock_client.chat.side_effect = identity_model
        mock_client.summary.api_calls = 1
        mock_client.summary.prompt_tokens = 10
        mock_client.summary.completion_tokens = 5
        mock_client.summary.cost_usd = 0.0

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        content = src.read_text()
        assert code_block in content

    def test_table_preserved_through_rewrite(self, tmp_path: Path) -> None:
        table = "| A | B |\n|---|---|\n| 1 | 2 |\n"
        src = tmp_path / "page.md"
        src.write_text(f"Intro.\n\n{table}\nOutro.\n", encoding="utf-8")

        def identity_model(**kwargs: Any) -> ChatResult:  # pyright: ignore[reportAny]
            user_text: str = kwargs["user"]
            import re

            parts = re.split(r"(__MDD_PROTECTED_\d+__)", user_text)
            out = "".join(p if p.startswith("__MDD_PROTECTED_") else p.upper() for p in parts)
            return _make_chat_result(out)

        mock_client = MagicMock()
        mock_client.chat.side_effect = identity_model
        mock_client.summary.api_calls = 1
        mock_client.summary.prompt_tokens = 10
        mock_client.summary.completion_tokens = 5
        mock_client.summary.cost_usd = 0.0

        result = rewrite_file(src, mock_client, apply=True)  # pyright: ignore[reportArgumentType]

        assert result.status == "rewritten"
        content = src.read_text()
        assert table in content


# ---------------------------------------------------------------------------
# rewrite_files
# ---------------------------------------------------------------------------


class TestRewriteFiles:
    def test_processes_all_files(self, tmp_path: Path) -> None:
        a = tmp_path / "a.md"
        b = tmp_path / "b.md"
        a.write_text("File A content.\n", encoding="utf-8")
        b.write_text("File B content.\n", encoding="utf-8")

        mock_client = _make_mock_client("Rewritten content.\n")

        results = rewrite_files([a, b], mock_client)  # pyright: ignore[reportArgumentType]

        assert len(results) == 2
        assert all(r.status == "rewritten" for r in results)

    def test_error_in_one_does_not_stop_others(self, tmp_path: Path) -> None:
        a = tmp_path / "a.md"
        b = tmp_path / "missing.md"  # does not exist
        c = tmp_path / "c.md"
        a.write_text("Content A.\n", encoding="utf-8")
        c.write_text("Content C.\n", encoding="utf-8")

        mock_client = _make_mock_client("Rewritten.\n")

        results = rewrite_files([a, b, c], mock_client)  # pyright: ignore[reportArgumentType]

        assert len(results) == 3
        assert results[0].status == "rewritten"
        assert results[1].status == "error"
        assert results[2].status == "rewritten"

    def test_serial_execution_order(self, tmp_path: Path) -> None:
        """Files must be processed in the order given (serial, not parallel)."""
        order: list[str] = []

        def ordered_chat(**kwargs: Any) -> ChatResult:  # pyright: ignore[reportAny]
            user: str = kwargs["user"]
            order.append(user[:6])  # first chars identify the file
            return _make_chat_result("Done.\n")

        mock_client = MagicMock()
        mock_client.chat.side_effect = ordered_chat
        mock_client.summary.api_calls = 0
        mock_client.summary.prompt_tokens = 0
        mock_client.summary.completion_tokens = 0
        mock_client.summary.cost_usd = 0.0

        files: list[Path] = []
        for i in range(3):
            p = tmp_path / f"file{i}.md"
            p.write_text(f"file{i} content here.\n", encoding="utf-8")
            files.append(p)

        rewrite_files(files, mock_client)  # pyright: ignore[reportArgumentType]

        # Verify processing happened in order (each call contained file identifier)
        assert len(order) == 3
        assert order[0].startswith("file0")
        assert order[1].startswith("file1")
        assert order[2].startswith("file2")


# ---------------------------------------------------------------------------
# Integration test (skipped unless MDD_AI_TEST=1)
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestRewriteIntegration:
    def test_live_rewrite(self, tmp_path: Path) -> None:
        from mdd.ai.client import Client

        src = tmp_path / "test.md"
        src.write_text(
            "# Test Document\n\nThis is a document that is very verbose and "
            "contains many unnecessary words that could be removed.\n",
            encoding="utf-8",
        )

        client = Client()
        result = rewrite_file(src, client)

        assert result.status == "rewritten"
        assert result.output_path is not None
        assert result.output_path.exists()
